# This is a config for E2B sandbox template for ROMA-Chinese.
# You can use template ID (5efyoklxeppejs2prlu4) or template name (roma-chinese-e2b-s3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("roma-chinese-e2b-s3") # Sync sandbox
# sandbox = await AsyncSandbox.create("roma-chinese-e2b-s3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('roma-chinese-e2b-s3')

team_id = "10c72e9b-7c76-4dce-b9cf-815a783fcf8e"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "roma-chinese-e2b-s3"
template_id = "5efyoklxeppejs2prlu4"
